name: CLI-Smoke-Test

on:
  workflow_dispatch:
    inputs:
      branch_name:
        type: string
        default: "master"
        description: The branch we will checkout
    branches:
      - master
  push:
    branches:
      - master

jobs:
  run-smoke-test:
    name: Runs CLI Smoke Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 7
      - run: sh download-rehearsal-cli.sh ${{ github.event.inputs.branch_name }}
      - run: pnpm run update-resolutions
      - run: pnpm test
